### PR TITLE
Installation script for h-m-m on Linux

### PR DESCRIPTION
**Pull request by llagerlof**
This PR introduce a script called install.sh. It also include instructions to readme.md:

- Check if php is on PATH.
- Check if  xclip, xsel or wl-clipboard are on PATH.
- Check if /usr/local/bin exists, if not fallback to /usr/bin
- Copy h-m-m to destination directory (mentioned above).
- Make h-m-m executable.

### CODE REVIEW

**Comment by nadrad** [comment]
Thanks. Good idea. 

What do you think about including the cloning process in the script as well? Then we can give people a one-line command to run; e.g., a wget command that downloads the script and then pipes it to bash to run. Then the script takes care of everything else. 

Maybe it can even ask the user whether or not they want to have automatic updates, and if they give a positive answer, creates a scheduled task (crontab or that other thing with systemd) to run once a day and pull the latest version! It's probably reinventing the wheel, but sounds like an interesting experience :)

**Comment by llagerlof** [comment]
Now that um mentioned the possibility to clone the repository automatically, I had another idea. What if the installer script download the h-m-m file instead cloning the repo? Do you think it's cleaner that way? I mean, it makes sense for a one file application.

The automatic updates it's an idea. I am not very comfortable to implement this since isn't a common behaviour in Linux environments, you know, to have things updating itself automatically. Maybe in the future.

**Comment by llagerlof** [comment]
2 commits added to this PR:

install.sh now download h-m-m if it does not exist in same directory as install.sh

**Comment by nadrad** [comment]
Thanks. 

Yes, it makes sense to only download the php file.

**Pull request merged**
