### PR TITLE
Added more support for MacOS in install script

### PR DESCRIPTION
**Pull request by gloof11**
I added a check for Homebrew, and if it exists, gives the option to install the corresponding dependencies.

### CODE REVIEW

**Comment by nadrad** [comment]
Thanks, but xclip and xsel are Linux requirements; if I understand it correctly, Mac always has `pbcopy` and `pbpaste`, and those are what *h-m-m* uses when detects a Mac. Maybe you can double-check and let me know.

**Comment by gloof11** [comment]
You're right! The only thing the install script doesn't do is check if the system is a Mac. That's why it wasn't working. I'll fix the script then push to the branch again.

**Comment by gloof11** [comment]
I had to change the interpreter to bash. It was the only way I could get the OS detection to work. Also, I made sure the script changed permissions on the binary so it was executable by users other than root.

**Comment by mattiasbonte** [comment]
Can this be merged?

**Comment by nadrad** [comment]
But it still seems to be requiring `xclip`, `xsel`, or `wl-clipboard` for Mac (lines 31 to 39).

**Pull request closed without merging**
